const prisma = require("../config/db");
const blockchainService = require("./blockchain.service");
const creditCalculationService = require("./creditCalculation.service");

class CarbonCreditService {
  /**
   * Calculates recommended carbon credits using scientific IPCC Tier 2 / Verra VM0033 formula
   */
  async calculateCredits(projectId) {
    return creditCalculationService.calculateForProject(projectId);
  }

  /**
   * Mints tokenized Blue Carbon credits for an approved project on Polygon Amoy
   */
  async mintProjectCredits(projectId, requestingUser, requestedAmount, overrideReason) {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        owner: true,
        verifications: { where: { decision: "APPROVED" }, take: 1 },
        satelliteReports: { orderBy: { reportDate: "desc" }, take: 1 },
      },
    });

    if (!project) {
      throw new Error("Project not found.");
    }

    if (project.status !== "APPROVED") {
      throw new Error(`Cannot mint carbon credits for project in '${project.status}' state. Project must be APPROVED by NCCR Verifier.`);
    }

    // 1. Run scientific calculation engine
    const calculation = await creditCalculationService.calculateForProject(projectId);
    const calculatedAmount = calculation.recommendedCredits;

    // 2. Validate amount & override justification
    const amountToMint = requestedAmount ? parseFloat(requestedAmount) : calculatedAmount;
    const isOverridden = Math.abs(amountToMint - calculatedAmount) > 0.01;

    if (isOverridden) {
      if (!overrideReason || overrideReason.trim().length < 15) {
        throw new Error(
          `Mandatory justification required: You are overriding the scientific recommendation of ${calculatedAmount} tCO₂e with ${amountToMint} tCO₂e. Please provide a detailed justification (minimum 15 characters).`
        );
      }
    }

    // Numeric Token ID derived from Project UUID
    const numericTokenId = parseInt(projectId.replace(/-/g, "").substring(0, 8), 16) % 1000000;

    // 3. Build IPFS Metadata
    const metadata = {
      name: `KarbonShrunkhala Blue Carbon Credit — ${project.projectName}`,
      description: `Tokenized Blue Carbon Offset generated by ${project.ecosystemType} restoration in ${project.district}, ${project.state}, India.`,
      projectId: project.id,
      projectName: project.projectName,
      ecosystemType: project.ecosystemType,
      areaHectares: project.areaHectares,
      ownerOrganization: project.owner?.organizationName || project.owner?.fullName,
      verifiedBy: project.verifications[0]?.verifierId || "NCCR National Verifier",
      methodologyVersion: calculation.methodologyVersion,
      calculatedAmount,
      mintedAmount: amountToMint,
      isOverridden,
      overrideReason: isOverridden ? overrideReason : null,
      geeSatelliteNDVI: calculation.parameters.meanNdvi,
      mintedAt: new Date().toISOString(),
    };

    // 4. Upload Metadata to IPFS
    const ipfsUri = await blockchainService.pinMetadataToIPFS(metadata);

    // 5. Mint Token on Polygon Amoy Testnet
    const mintResult = await blockchainService.mintCarbonCreditOnChain({
      recipientAddress: null, // Defaults to platform deployer wallet
      tokenId: numericTokenId,
      amount: Math.round(amountToMint),
      ipfsUri,
    });

    // 6. Save Record in PostgreSQL CarbonCredit Table with full calculation reproducibility
    const carbonCredit = await prisma.carbonCredit.create({
      data: {
        projectId: project.id,
        quantity: amountToMint,
        tokenId: `KBCC-AMOY-${numericTokenId}`,
        blockchainTx: mintResult.transactionHash,
        calculatedAmount,
        isOverridden,
        overrideReason: isOverridden ? overrideReason.trim() : null,
        calculationInputs: calculation.parameters,
        methodologyVersion: calculation.methodologyVersion,
      },
    });

    // 7. Log System Audit Entry
    await prisma.auditLog.create({
      data: {
        userId: requestingUser.id,
        action: isOverridden ? "CARBON_CREDIT_MINT_OVERRIDE" : "TOKEN_MINT_POLYGON_AMOY",
        entity: "CarbonCredit",
        entityId: carbonCredit.id,
      },
    }).catch(() => {});

    return {
      carbonCredit,
      calculation,
      onChain: mintResult,
    };
  }

  /**
   * Fetch all carbon credits issued to a specific user/organization
   */
  async getUserCredits(userId) {
    return prisma.carbonCredit.findMany({
      where: { project: { ownerId: userId } },
      include: {
        project: { select: { id: true, projectName: true, ecosystemType: true, state: true, district: true, owner: true } },
      },
      orderBy: { issuedAt: "desc" },
    });
  }

  /**
   * Fetch all tokenized carbon credits on the platform
   */
  async getAllCredits() {
    return prisma.carbonCredit.findMany({
      include: {
        project: { select: { id: true, projectName: true, ecosystemType: true, state: true, district: true, owner: true } },
      },
      orderBy: { issuedAt: "desc" },
    });
  }
}

module.exports = new CarbonCreditService();
