const prisma = require("../config/db");
const blockchainService = require("./blockchain.service");

class CarbonCreditService {
  /**
   * Mints tokenized Blue Carbon credits for an approved project on Polygon Amoy
   */
  async mintProjectCredits(projectId, requestingUser, requestedAmount) {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        owner: true,
        verifications: { where: { decision: "APPROVED" }, take: 1 },
        satelliteReports: { orderBy: { reportDate: "desc" }, take: 1 },
      },
    });

    if (!project) {
      throw new Error("Project not found.");
    }

    if (project.status !== "APPROVED") {
      throw new Error(`Cannot mint carbon credits for project in '${project.status}' state. Project must be APPROVED by NCCR Verifier.`);
    }

    // Determine credit quantity (1 credit = 1 tCO2e)
    const amountToMint = parseInt(requestedAmount || project.baselineCarbonStock || Math.round(project.areaHectares * 10) || 100);

    // Numeric Token ID derived from Project UUID
    const numericTokenId = parseInt(projectId.replace(/-/g, "").substring(0, 8), 16) % 1000000;

    // 1. Build IPFS Metadata
    const metadata = {
      name: `KarbonShrunkhala Blue Carbon Credit — ${project.projectName}`,
      description: `Tokenized Blue Carbon Offset generated by ${project.ecosystemType} restoration in ${project.district}, ${project.state}, India.`,
      projectId: project.id,
      projectName: project.projectName,
      ecosystemType: project.ecosystemType,
      areaHectares: project.areaHectares,
      ownerOrganization: project.owner?.organizationName || project.owner?.fullName,
      verifiedBy: project.verifications[0]?.verifierId || "NCCR National Verifier",
      geeSatelliteNDVI: project.satelliteReports[0]?.meanNdvi || 0.74,
      mintedAt: new Date().toISOString(),
    };

    // 2. Upload Metadata to IPFS
    const ipfsUri = await blockchainService.pinMetadataToIPFS(metadata);

    // 3. Mint Token on Polygon Amoy Testnet
    const mintResult = await blockchainService.mintCarbonCreditOnChain({
      recipientAddress: null, // Defaults to platform deployer wallet
      tokenId: numericTokenId,
      amount: amountToMint,
      ipfsUri,
    });

    // 4. Save Record in PostgreSQL CarbonCredit Table matching exact Prisma Schema
    const carbonCredit = await prisma.carbonCredit.create({
      data: {
        projectId: project.id,
        quantity: amountToMint,
        tokenId: `KBCC-AMOY-${numericTokenId}`,
        blockchainTx: mintResult.transactionHash,
      },
    });

    // 5. Log System Audit Entry
    await prisma.auditLog.create({
      data: {
        userId: requestingUser.id,
        action: "TOKEN_MINT_POLYGON_AMOY",
        entity: "CarbonCredit",
        entityId: carbonCredit.id,
      },
    }).catch(() => {});

    return {
      carbonCredit,
      onChain: mintResult,
    };
  }

  /**
   * Fetch all carbon credits issued to a specific user/organization
   */
  async getUserCredits(userId) {
    return prisma.carbonCredit.findMany({
      where: { project: { ownerId: userId } },
      include: {
        project: { select: { id: true, projectName: true, ecosystemType: true, state: true, district: true, owner: true } },
      },
      orderBy: { issuedAt: "desc" },
    });
  }

  /**
   * Fetch all tokenized carbon credits on the platform
   */
  async getAllCredits() {
    return prisma.carbonCredit.findMany({
      include: {
        project: { select: { id: true, projectName: true, ecosystemType: true, state: true, district: true, owner: true } },
      },
      orderBy: { issuedAt: "desc" },
    });
  }
}

module.exports = new CarbonCreditService();
